sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libglu1-mesa-dev
    - freeglut3-dev
    - mesa-common-dev
script:
  - make outs
  - make main
